import "./globals.css";
import type { Metadata } from "next";
import { plusJakarta } from "./ui/homepage/fonts";
import { link } from "fs";

export const metadata: Metadata = {
  title: "PPJS HKBP - Official Website",
  icons: {
    icon: "/images/Logo-HKBP.webp",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={plusJakarta.className}>
        <div className="md:h-[95%]">{children}</div>
      </body>
    </html>
  );
}
