import "./globals.css";
import type { Metadata } from "next";
import { plusJakarta } from "./ui/fonts";
import NavBar from "./ui/navbar";
import Footer from "./ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={plusJakarta.className}>
        <div className="md:h-[5%]">
          <NavBar />
        </div>
        <div className="md:h-[95%]">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
